server:
  port: 8761
spring:
  application:
    name: first-cloud-server
  profiles: slave1
eureka:
  instance:
    hostname: slave1
  client:
    eureka-server-u-r-l-context: http://slave2:8762/eureka/

---

server:
  port: 8762
spring:
  application:
    name: first-cloud-server
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  client:
    eureka-server-u-r-l-context: http://slave1:8761/eureka/